#!/bin/sh

touch "$HOME"/.psqlrc.local

if [ ! -e "$HOME"/.local/share/nvim/site/autoload/plug.vim ]; then
  curl -fLo "$HOME"/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
"$HOME"/bin/./nvim/bin/nvim -u "$HOME"/.config/nvim/init.vim +PlugUpdate +PlugClean! +qa

# reset -Q
