#!/bin/sh

set -e

local_hook="$HOME"/.git_template.local/hooks/pre-commit

if [ -f "$local_hook" ]; then
  . "$local_hook"
fi

echo "Running i18n-tasks normalize..."

# Format i18n keys using i18n-tasks
i18n-tasks normalize

status=$?

if [ "$status" = 0 ] ; then
    echo "Your i18n keys have been normalized."
    exit 0
fi
